### ISSUE TITLE
Payload may not be larger than 32767 bytes cause by Shulker box only 

### ISSUE THREAD

**Issue by JoeSGT** [progwml6/ironchest#143]
So im getting this error with lasso from Extra Utilities mod and animal nets from Hatchery basically with animal nets you can have up to about 3 stacks of them put it only any shulker box that is in IronChest mod 
and then you will get that error i put in the title, tested it and was only able to recreate it with IronChest Mod Shulker box more information can be found here

https://github.com/GenDeathrow/Hatchery/issues/157

please fix because with this error anyone can crash there base and make it hard for player to fix them.

**Comment by alexbegt** [comment]
You are running on a server correct?

**Comment by alexbegt** [comment]
Also, What version of Iron Chest are you running?

**Comment by JoeSGT** [comment]
I have done this both server and client singleplayer

Tested with ironchest-1.12.2-7.0.42.827

EDIT: just also test ironchest-1.12.2-7.0.44.829 latest release on curseforge

with those version that i had tested with i can still do it the bug

**Comment by alexbegt** [comment]
Can you upload a save file so I can test? I am unable to recreate the crash on my end . Also, are you running a mod pack or just a bunch of mods? Can I have a complete list of them?

**Comment by JoeSGT** [comment]
Okay after few testing i had figure it out on why can't you reproduce the issue it seem there another mod causing the issue this and it's theoneprobe I'll link the mod below and the version that i had use for that is 1.12-1.4.23 currently latest version on curseforge here how to reproduce it i installed The One Probe mod and IronChest mod along with Hatchery, then i went into singleplayer grab an animal nets and use a vanilla chicken egg spawn it then use the animal net's to catch it then i grab a Shulker box from IronChest mod i place it down and then i look at it so the one probe is detecting it and giving you the information
that it's displaying then while i was in creative doing all this i put the animal net's inside it was a stack of 16 and i had 4 stacks of them then i spread them cross the box i had also made a test guide world
[New World.zip](https://github.com/progwml6/ironchest/files/2109346/New.World.zip)
the mods that i had use is
```
 theoneprobe-1.12-1.4.23
ironchest-1.12.2-7.0.44.829 
hatchery-1.12.2-2.1.2
```
https://minecraft.curseforge.com/projects/the-one-probe

**Comment by Desim8r** [comment]
Having the same issue in Craft if the Titans II. (also includes The One Probe)
Error occurred just after I placed some eggs from the hatchery mod into a shulker box and every time I try to reload that instance.

19:37:59] [Netty Local Client IO #0/ERROR]: NetworkDispatcher exception
java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes
	at net.minecraft.network.play.client.CPacketCustomPayload.<init>(CPacketCustomPayload.java:28) ~[lh.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLProxyPacket.toC17Packet(FMLProxyPacket.java:142) ~[FMLProxyPacket.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.write(NetworkDispatcher.java:534) ~[NetworkDispatcher.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at net.minecraft.network.NetworkManager$4.run(NetworkManager.java:245) [gw$4.class:?]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
[19:37:59] [Server thread/INFO]: Sim lost connection: Disconnected

**Comment by JoeSGT** [comment]
Going to close this because the one probe has made an update to fix this. Whoever having this issue be sure that you are on version 1.12.2-1.4.25 or above. This commit fix it if your wondering https://github.com/McJtyMods/TheOneProbe/commit/09db053894cceb39cd2a2d49588f4b1f649897f1
