### ISSUE TITLE
help my proble crash

### ISSUE THREAD

**Issue by bentomusique** [progwml6/ironchest#194]
messag error The game crashed whilst unexpected error
Error: java.lang.AbstractMethodError: Method net/minecraft/block/state/BlockStateContainer$StateImplementation.doesSideBlockChestOpening(Lnet/minecraft/world/IBlockAccess;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/EnumFacing;)Z is abstract

**Comment by progwml6** [comment]
please provide the full crash log

**Comment by bentomusique** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  CXLibraryCore (CXLibrary-1.12.1.jar)
  Inventory Tweaks Coremod (Inventory-Tweaks-Mod-1.12.2.jar)
  SpongeCoremod (spongeforge-1.12.2-2825-7.1.6-RC3688.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 7/29/19 8:01 PM
Description: Unexpected error

java.lang.AbstractMethodError: Method net/minecraft/block/state/BlockStateContainer$StateImplementation.doesSideBlockChestOpening(Lnet/minecraft/world/IBlockAccess;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/EnumFacing;)Z is abstract
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.doesSideBlockChestOpening(BlockStateContainer.java)
	at cpw.mods.ironchest.common.blocks.chest.BlockIronChest.func_180639_a(BlockIronChest.java:127)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:423)
	at PlayerControllerOF.func_187099_a(PlayerControllerOF.java:87)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1578)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2253)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2019)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1807)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.doesSideBlockChestOpening(BlockStateContainer.java)
	at cpw.mods.ironchest.common.blocks.chest.BlockIronChest.func_180639_a(BlockIronChest.java:127)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:423)
	at PlayerControllerOF.func_187099_a(PlayerControllerOF.java:87)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1578)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2253)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2019)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['MiraMusique'/1374, l='MpServer', x=4316.21, y=61.00, z=2703.24]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-1,63,0), Chunk: (at 15,3,0 in -1,0; contains blocks -16,0,0 to -1,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 17423007 game time, 8173109 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 86 total; [EntitySkeleton['Skeleton'/1542, l='MpServer', x=4335.92, y=25.00, z=2720.55], EntitySkeleton['Skeleton'/1543, l='MpServer', x=4331.50, y=28.00, z=2736.50], MoCEntitySilverSkeleton['SilverSkeleton'/1544, l='MpServer', x=4322.50, y=65.00, z=2749.50], EntityCreeper['Creeper'/1545, l='MpServer', x=4322.50, y=15.00, z=2755.50], EntityZombie['Zombie'/1546, l='MpServer', x=4324.50, y=16.00, z=2754.50], MoCEntitySilverSkeleton['SilverSkeleton'/1547, l='MpServer', x=4323.50, y=65.00, z=2752.50], EntityCreeper['Creeper'/1675, l='MpServer', x=4288.50, y=23.00, z=2761.50], EntityCreeper['Creeper'/1676, l='MpServer', x=4289.50, y=23.00, z=2762.50], MoCEntityBunny['Bunny'/1552, l='MpServer', x=4348.38, y=62.88, z=2724.49], MoCEntityHorseMob['HorseMob'/1680, l='MpServer', x=4365.13, y=16.00, z=2767.15], MoCEntityDeer['Deer'/1553, l='MpServer', x=4349.14, y=62.12, z=2720.79], MoCEntityScorpion['Scorpion'/1554, l='MpServer', x=4347.50, y=32.00, z=2764.50], EntitySkeleton['Skeleton'/1810, l='MpServer', x=4359.50, y=43.00, z=2749.50], EntitySkeleton['Skeleton'/1811, l='MpServer', x=4359.50, y=43.00, z=2751.50], EntitySheep['Sheep'/1556, l='MpServer', x=4336.19, y=78.00, z=2777.69], EntitySheep['Sheep'/1557, l='MpServer', x=4350.39, y=83.00, z=2781.71], EntityZombie['Zombie'/1689, l='MpServer', x=4354.50, y=27.00, z=2774.50], EntitySkeleton['Skeleton'/1562, l='MpServer', x=4357.50, y=28.00, z=2679.50], EntitySkeleton['Skeleton'/1690, l='MpServer', x=4355.50, y=27.00, z=2777.50], EntitySkeleton['Skeleton'/1563, l='MpServer', x=4358.50, y=28.00, z=2679.50], MoCEntityAnt['Ant'/1564, l='MpServer', x=4367.50, y=64.00, z=2726.00], EntitySkeleton['Skeleton'/1565, l='MpServer', x=4365.50, y=15.00, z=2782.50], MoCEntityGoldFish['GoldFish'/1567, l='MpServer', x=4371.32, y=61.26, z=2697.27], MoCEntityGoldFish['GoldFish'/1568, l='MpServer', x=4372.29, y=61.60, z=2708.35], EntityCow['Cow'/1569, l='MpServer', x=4382.50, y=70.00, z=2741.20], MoCEntityAnt['Ant'/1570, l='MpServer', x=4375.46, y=74.00, z=2773.52], EntityCreeper['Creeper'/1459, l='MpServer', x=4236.50, y=20.00, z=2724.50], MoCEntityBird['Bird'/1466, l='MpServer', x=4241.20, y=74.00, z=2648.20], MoCEntityAngler['Angler'/1467, l='MpServer', x=4254.05, y=61.58, z=2681.59], MoCEntityAngler['Angler'/1468, l='MpServer', x=4246.00, y=62.47, z=2699.50], MoCEntityGoldFish['GoldFish'/1469, l='MpServer', x=4255.63, y=62.08, z=2693.81], MoCEntityMouse['Mouse'/1470, l='MpServer', x=4240.92, y=63.11, z=2712.02], EntityCreeper['Creeper'/1471, l='MpServer', x=4243.50, y=19.00, z=2756.50], EntityCreeper['Creeper'/1472, l='MpServer', x=4241.50, y=19.00, z=2759.50], EntitySpider['Spider'/1473, l='MpServer', x=4240.50, y=78.00, z=2761.50], MoCEntityGoldFish['GoldFish'/1477, l='MpServer', x=4261.00, y=61.71, z=2673.82], MoCEntityAngler['Angler'/1478, l='MpServer', x=4259.24, y=61.10, z=2681.78], MoCEntityAnt['Ant'/1479, l='MpServer', x=4267.27, y=63.00, z=2733.85], MoCEntitySilverSkeleton['SilverSkeleton'/1480, l='MpServer', x=4261.50, y=20.00, z=2736.50], EntityItem['item.item.arrow'/1481, l='MpServer', x=4260.93, y=72.00, z=2748.43], EntityItem['item.item.bone'/1482, l='MpServer', x=4260.39, y=74.00, z=2749.44], MoCEntityAngelFish['AngelFish'/1488, l='MpServer', x=4281.50, y=61.97, z=2651.50], EntityCreeper['Creeper'/1744, l='MpServer', x=4362.50, y=39.00, z=2742.50], MoCEntityAngelFish['AngelFish'/1489, l='MpServer', x=4282.50, y=61.98, z=2654.50], MoCEntityAngelFish['AngelFish'/1490, l='MpServer', x=4281.50, y=61.82, z=2655.50], MoCEntityAngler['Angler'/1491, l='MpServer', x=4277.31, y=61.32, z=2655.12], EntityPlayerSP['MiraMusique'/1374, l='MpServer', x=4316.21, y=61.00, z=2703.24], MoCEntityGoldFish['GoldFish'/1492, l='MpServer', x=4277.75, y=61.80, z=2654.56], MoCEntityAngelFish['AngelFish'/1493, l='MpServer', x=4276.50, y=60.95, z=2658.50], MoCEntityDeer['Deer'/1494, l='MpServer', x=4276.52, y=64.00, z=2735.59], MoCEntityAnt['Ant'/1495, l='MpServer', x=4286.50, y=63.00, z=2750.49], EntityZombie['Zombie'/1751, l='MpServer', x=4270.50, y=19.00, z=2623.50], MoCEntityBird['Bird'/1496, l='MpServer', x=4283.84, y=64.00, z=2745.22], EntityCreeper['Creeper'/1754, l='MpServer', x=4236.50, y=61.00, z=2735.50], MoCEntityBass['Bass'/1502, l='MpServer', x=4288.86, y=60.87, z=2629.00], MoCEntityManderin['Manderin'/1503, l='MpServer', x=4301.50, y=61.98, z=2654.50], MoCEntityManderin['Manderin'/1504, l='MpServer', x=4299.50, y=61.87, z=2654.50], MoCEntityManderin['Manderin'/1505, l='MpServer', x=4298.91, y=61.40, z=2652.88], MoCEntityManderin['Manderin'/1506, l='MpServer', x=4294.45, y=61.26, z=2661.72], MoCEntityManderin['Manderin'/1507, l='MpServer', x=4291.83, y=62.12, z=2661.02], MoCEntityManderin['Manderin'/1508, l='MpServer', x=4298.33, y=61.42, z=2669.18], EntityCreeper['Creeper'/1509, l='MpServer', x=4296.50, y=35.00, z=2758.50], EntityCow['Cow'/1510, l='MpServer', x=4301.65, y=68.00, z=2755.50], MoCEntityGoat['Goat'/1511, l='MpServer', x=4290.50, y=66.00, z=2752.50], MoCEntitySnail['Snail'/1512, l='MpServer', x=4294.50, y=68.00, z=2766.50], MoCEntityBunny['Bunny'/1513, l='MpServer', x=4298.00, y=70.00, z=2772.97], MoCEntityBunny['Bunny'/1514, l='MpServer', x=4302.30, y=70.00, z=2774.33], MoCEntityAnt['Ant'/1515, l='MpServer', x=4290.50, y=67.00, z=2782.50], MoCEntityMouse['Mouse'/1516, l='MpServer', x=4297.70, y=70.00, z=2772.12], EntitySkeleton['Skeleton'/1775, l='MpServer', x=4363.50, y=39.00, z=2775.50], EntityZombie['Zombie'/1776, l='MpServer', x=4358.50, y=39.00, z=2767.50], EntityZombie['Zombie'/1777, l='MpServer', x=4357.50, y=39.00, z=2770.50], MoCEntityManderin['Manderin'/1523, l='MpServer', x=4318.85, y=62.00, z=2653.00], MoCEntityGoldFish['GoldFish'/1524, l='MpServer', x=4308.62, y=61.32, z=2659.62], MoCEntityGoldFish['GoldFish'/1525, l='MpServer', x=4310.85, y=62.00, z=2666.60], EntityCreeper['Creeper'/1781, l='MpServer', x=4368.50, y=39.00, z=2734.50], MoCEntityBunny['Bunny'/1526, l='MpServer', x=4305.99, y=67.00, z=2707.75], MoCEntityBunny['Bunny'/1527, l='MpServer', x=4305.43, y=67.00, z=2706.27], MoCEntityBunny['Bunny'/1528, l='MpServer', x=4305.84, y=67.00, z=2707.10], PaddockSignEntity['Paddock Sign'/1529, l='MpServer', x=4311.03, y=68.50, z=2707.50], MoCEntityCricket['Cricket'/1530, l='MpServer', x=4318.70, y=70.00, z=2747.57], EntityZombie['Zombie'/1531, l='MpServer', x=4308.50, y=31.00, z=2766.50], EntityCreeper['Creeper'/1532, l='MpServer', x=4314.50, y=28.00, z=2758.50], EntitySkeleton['Skeleton'/1533, l='MpServer', x=4317.50, y=28.00, z=2753.50], MoCEntityBee['Bee'/1534, l='MpServer', x=4308.24, y=71.00, z=2775.35], MoCEntityCricket['Cricket'/1535, l='MpServer', x=4318.10, y=71.34, z=2781.59]]
	Retry entities: 0 total; []
	Server brand: fml,forge,sponge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:527)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2740)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1557791896 bytes (1485 MB) / 2751463424 bytes (2624 MB) up to 10737418240 bytes (10240 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2772 Optifine OptiFine_1.12.2_HD_U_C5 33 mods loaded, 33 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID              | Version                  | Source                                        | Signature                                |
	|:------ |:--------------- |:------------------------ |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft       | 1.12.2                   | minecraft.jar                                 | None                                     |
	| UCHIJA | mcp             | 9.42                     | minecraft.jar                                 | None                                     |
	| UCHIJA | FML             | 8.0.99.99                | forge-1.12.2-14.23.5.2772.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge           | 14.23.5.2772             | forge-1.12.2-14.23.5.2772.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | spongeapi       | 7.1.0-4ab0d1a5           | spongeforge-1.12.2-2825-7.1.6-RC3688.jar      | None                                     |
	| UCHIJA | sponge          | 1.12.2-7.1.6-SNAPSHOT    | spongeforge-1.12.2-2825-7.1.6-RC3688.jar      | None                                     |
	| UCHIJA | spongeforge     | 1.12.2-2825-7.1.6-RC3688 | spongeforge-1.12.2-2825-7.1.6-RC3688.jar      | None                                     |
	| UCHIJA | backpack        | 3.0.2                    | Backpacks-Mod-1.12.2.jar                      | None                                     |
	| UCHIJA | bibliocraft     | 2.4.5                    | BiblioCraft-Mod-1.12.2.jar                    | None                                     |
	| UCHIJA | codechickenlib  | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA | customspawner   | 3.11.4                   | Custom-Mob-Spawner-Mod-1.12.2.jar             | None                                     |
	| UCHIJA | cxlibrary       | 1.6.1                    | CXLibrary-1.12.1.jar                          | None                                     |
	| UCHIJA | gottschcore     | 1.3.5                    | GottschCore-mc1.12.2-f14.23.2.2611-v1.3.5.jar | None                                     |
	| UCHIJA | dungeons2       | 1.3.3                    | Dungeons2-mc1.12.2-f14.23.1.2555-v1.3.3.jar   | None                                     |
	| UCHIJA | jei             | 4.15.0.268               | jei_1.12.2-4.15.0.268.jar                     | None                                     |
	| UCHIJA | nei             | 2.4.2                    | NotEnoughItems-1.12.2-2.4.2.240-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA | ftblib          | 5.2.0.31                 | FTBLib-1.12.2.jar                             | None                                     |
	| UCHIJA | journeymap      | 1.12.2-5.5.4             | journeymap-1.12.2-5.5.4.jar                   | None                                     |
	| UCHIJA | ftbutilities    | 5.2.0.37                 | FTB-Utilities-Mod-1.12.2.jar                  | None                                     |
	| UCHIJA | cfm             | 6.3.0                    | furniture-6.3.0-1.12.2.jar                    | None                                     |
	| UCHIJA | waila           | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                   | None                                     |
	| UCHIJA | inventorytweaks | 1.63+release.109.220f184 | Inventory-Tweaks-Mod-1.12.2.jar               | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJA | ironchest       | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.69.845.jar               | None                                     |
	| UCHIJA | jmcm            | 9.2                      | MinecraftCapes Forge 1.12.2.jar               | None                                     |
	| UCHIJA | mocreatures     | 12.0.5                   | Mo-Creatures-Mod-1.12.2.jar                   | None                                     |
	| UCHIJA | morefurnaces    | 1.10.5                   | More-Furnaces-Mod-1.12.2.jar                  | None                                     |
	| UCHIJA | placebo         | 1.6.0                    | Placebo-1.12.2.jar                            | None                                     |
	| UCHIJA | plants2         | 2.10.6                   | Plants-Mod-1.12.2.jar                         | None                                     |
	| UCHIJA | simplecore      | 1.7.3.4                  | SimpleCore-API-1.12.2.jar                     | None                                     |
	| UCHIJA | simpleores      | 1.11.2.2                 | simpleores-1.12.2-1.11.2.2.jar                | None                                     |
	| UCHIJA | worldprotector  | 1.0                      | WorldProtector+(1.12).jar                     | None                                     |
	| UCHIJA | llibrary        | 1.7.19                   | llibrary-1.7.19-1.12.2.jar                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| UCHIJA | jurassicraft    | 2.1.23                   | JurassiCraft-1.12.2-2.1.23.jar                | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
CXLibraryCore (CXLibrary-1.12.1.jar)
  cubex2.cxlibrary.CoreModTransformer
Inventory Tweaks Coremod (Inventory-Tweaks-Mod-1.12.2.jar)
  invtweaks.forge.asm.ContainerTransformer
SpongeCoremod (spongeforge-1.12.2-2825-7.1.6-RC3688.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 419.35' Renderer: 'GeForce GTX 1070/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2772
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1070/PCIe/SSE2 GL version 4.6.0 NVIDIA 419.35, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge,sponge'
	Type: Client (map_client.txt)
	Resource Packs: Aarons+Quadral+v.4.2+MC1.12.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_C5
	Render Distance Chunks: 21
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: DocteurDreads-Shaders-Low.zip
	OpenGlVersion: 4.6.0 NVIDIA 419.35
	OpenGlRenderer: GeForce RTX 2080/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by bentomusique** [comment]
> 
> 
> please provide the full crash log

**Comment by bentomusique** [comment]
you had a solution
