### ISSUE TITLE
1.8.9 crash

### ISSUE THREAD

**Issue by Ideki** [progwml6/ironchest#65]
I have IronChest 1.8-6.0.99.749-universal
Each time I start minecraft, it crashes before even showing me the game menu (single player, servers,...)
If I remove the mod, the game starts without any problem.
I removed optifine, and tried again with ironchest, issue happened again.
So the problem is 100% related to ironchest.
This is the error reported:

> ---- Minecraft Crash Report ----

WARNING: coremods are present:
  ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)
  FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  CoreXU2 (extrautils2-1.8.9-alpha-0.0.1.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 3/28/16 7:47 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: cpw/mods/ironchest/TileEntityIronChest
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:162)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:739)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:310)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:495)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: cpw/mods/ironchest/TileEntityIronChest
	at cpw.mods.ironchest.IronChestType.<clinit>(IronChestType.java:29)
	at cpw.mods.ironchest.ChestChangerType.<clinit>(ChestChangerType.java:25)
	at cpw.mods.ironchest.IronChest.load(IronChest.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:737)
	... 10 more
Caused by: java.lang.ClassNotFoundException: cpw.mods.ironchest.TileEntityIronChest
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 39 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/gui/IUpdatePlayerListBox
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 41 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.gui.IUpdatePlayerListBox
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 45 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1650787856 bytes (1574 MB) / 2134114304 bytes (2035 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -Xms2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.1764 23 mods loaded, 23 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1764.jar) 
	UCHI	Forge{11.15.1.1764} [Minecraft Forge] (forge-1.8.9-11.15.1.1764.jar) 
	UCHI	CoreXU2{1} [CoreXU2] (minecraft.jar) 
	UCHI	BuildCraft|Core{7.2.3} [BuildCraft] (buildcraft-7.2.3.jar) 
	UCHI	BuildCraft|Builders{7.2.3} [BC Builders] (buildcraft-7.2.3.jar) 
	UCHI	BuildCraft|Transport{7.2.3} [BC Transport] (buildcraft-7.2.3.jar) 
	UCHI	BuildCraft|Energy{7.2.3} [BC Energy] (buildcraft-7.2.3.jar) 
	UCHI	BuildCraft|Silicon{7.2.3} [BC Silicon] (buildcraft-7.2.3.jar) 
	UCHI	BuildCraft|Robotics{7.2.3} [BC Robotics] (buildcraft-7.2.3.jar) 
	UCHI	BuildCraft|Factory{7.2.3} [BC Factory] (buildcraft-7.2.3.jar) 
	UCHI	exnihilo2{0.28} [Ex Nihilo 2] (ExNihilo2-0.28.jar) 
	UCHI	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.8.9-alpha-0.0.1.jar) 
	UCHI	fastleafdecay{1.6} [Fast Leaf Decay] (FastLeafDecay-1.8-1.6.jar) 
	UCHE	IronChest{6.0.99.749} [Iron Chest] (ironchest-1.8-6.0.99.749-universal.jar) 
	UCHI	JEI{2.28.7.174} [Just Enough Items] (jei_1.8.9-2.28.7.174.jar) 
	UCHI	journeymap{1.8.9-5.1.5} [JourneyMap] (journeymap-1.8.9-5.1.5-unlimited.jar) 
	UCHI	mantle{1.8.9-0.9.2.jenkins102} [Mantle] (Mantle-1.8.9-0.9.2.jar) 
	UCHI	tconstruct{1.8.9-2.2.0.jenkins135} [Tinkers' Construct] (TConstruct-1.8.9-2.2.0b.jar) 
	UCHI	Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
	UCHI	Thaumcraft{5.2.4} [Thaumcraft] (Thaumcraft-1.8.9-5.2.4.jar) 
	UCHI	Waila{1.6.0} [Waila] (Waila-1.6.0-B3_1.8.8.jar) 
	UCHI	denseores{1.0} [denseores] (denseores-1.8-alpha-2.0.3.jar) 
	Loaded coremods (and transformers): 
ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)
  
FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  com.olafski.fastleafdecay.FldTransformer
CoreXU2 (extrautils2-1.8.9-alpha-0.0.1.jar)
  com.rwtema.extrautils2.asm.ClassTransformerHandler
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 364.51' Renderer: 'GeForce GTX 770/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)

**Comment by alexbegt** [comment]
Think you can try 'ironchest-1.8.9-6.0.125.770.jar' from CurseForge @Ideki?

**Comment by Ideki** [comment]
'ironchest-1.8.9-6.0.125.770.jar' looks ok.
Game is loading, and I cannot see the recipes for ironchest in jei.
Thanks

**Comment by alexbegt** [comment]
You should've been able to see the recipes in JEI, that's very weird.

**Comment by Ideki** [comment]
Doh, stupid me, I meant that I see the recipes :)

**Comment by alexbegt** [comment]
It's okay, everyone makes mistake :)
