### ISSUE TITLE
Crash with crystal chests

### ISSUE THREAD

**Issue by siskulous** [progwml6/ironchest#96]
In the interests of giving as much detail as possible: from the log this crash is definitely related to the only crystal chest in this world. The chest in question has the output from a vindicator/wither skeleton farm (emeralds, iron axes, wither skulls, necrotic bones, drops of evil [Extra Utilities 2], wither dust [Dark Utilities], bones, and stone swords) being fed into it via an ender hopper. It has two item transfer nodes hooked up to it, one sucking emeralds out to a compacting drawer and the other sucking stone swords and unenchanted iron axes out to a trash can. Obviously there are a lot of mods interacting in this room, but the log is pointing the finger at the crystal chest, so I'm posting the issue here.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  FCFMLCorePlugin (FinderCompass-1.11.2.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.62+beta.86.jar)
  IvToolkit (IvToolkit-1.3.3.jar)
  BookshelfLoadingPlugin (Bookshelf-1.11.2-1.5.0.371.jar)
  PotionCoreFMLLoadingPlugin (PotionCore-1.5.2_for_1.11.2.jar)
  ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.4.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 6/14/17 7:40 AM
Description: Rendering Block Entity

java.lang.ArrayIndexOutOfBoundsException: 9
	at cpw.mods.ironchest.client.TileEntityIronChestRenderer.renderTileEntityAt(TileEntityIronChestRenderer.java:192)
	at cpw.mods.ironchest.client.TileEntityIronChestRenderer.func_180535_a(TileEntityIronChestRenderer.java:31)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:173)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:146)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:999)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1765)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1590)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1361)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at cpw.mods.ironchest.client.TileEntityIronChestRenderer.renderTileEntityAt(TileEntityIronChestRenderer.java:192)
	at cpw.mods.ironchest.client.TileEntityIronChestRenderer.func_180535_a(TileEntityIronChestRenderer.java:31)

-- Block Entity Details --
Details:
	Name: minecraft:ironchest.crystal // cpw.mods.ironchest.TileEntityCrystalChest
	Block type: ID #443 (tile.IronChest // cpw.mods.ironchest.BlockIronChest)
	Block data value: 5 / 0x5 / 0b0101
	Block location: World: (-215,67,415), Chunk: (at 9,4,15 in -14,25; contains blocks -224,0,400 to -209,255,415), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #443 (tile.IronChest // cpw.mods.ironchest.BlockIronChest)
	Actual block data value: 5 / 0x5 / 0b0101
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:173)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:146)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:999)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1765)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1590)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['JameMcDougal'/419, l='MpServer', x=-215.36, y=67.00, z=414.66]]
	Chunk stats: MultiplayerChunkCache: 361, 361
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (88,64,256), Chunk: (at 8,4,0 in 5,16; contains blocks 80,0,256 to 95,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 13880676 game time, 5934633 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 110 total; [EntityZombie['Zombie'/532, l='MpServer', x=-264.27, y=40.00, z=339.07], EntityMinecartHopper['Minecart with Hopper'/533, l='MpServer', x=-261.50, y=67.06, z=347.49], EntityPig['Pig'/542, l='MpServer', x=-137.78, y=72.00, z=480.46], EntityCow['Cow'/543, l='MpServer', x=-293.83, y=68.00, z=369.16], EntityVillager['Villager'/294, l='MpServer', x=-187.50, y=65.00, z=360.50], EntityVillager['Villager'/295, l='MpServer', x=-185.50, y=65.00, z=360.50], EntityVillager['Villager'/296, l='MpServer', x=-183.50, y=65.00, z=360.50], EntityVillager['Villager'/297, l='MpServer', x=-191.50, y=65.00, z=360.50], EntityVillager['Villager'/298, l='MpServer', x=-189.50, y=65.00, z=360.50], EntityZombie['Zombie'/555, l='MpServer', x=-281.50, y=35.00, z=351.50], EntityPig['Pig'/556, l='MpServer', x=-281.66, y=64.00, z=346.49], EntitySkeleton['Skeleton'/557, l='MpServer', x=-147.50, y=33.00, z=485.50], EntitySkeleton['Skeleton'/558, l='MpServer', x=-148.50, y=33.00, z=490.50], EntityWitch['Witch'/565, l='MpServer', x=-152.50, y=38.00, z=470.50], EntitySheep['Sheep'/566, l='MpServer', x=-153.28, y=73.00, z=478.46], EntityCreeper['Creeper'/580, l='MpServer', x=-185.33, y=17.00, z=493.85], EntitySheep['Sheep'/581, l='MpServer', x=-169.46, y=74.00, z=472.90], EntitySheep['Sheep'/583, l='MpServer', x=-152.50, y=65.00, z=442.27], EntityBat['Bat'/584, l='MpServer', x=-207.17, y=17.12, z=488.31], EntityPig['Pig'/586, l='MpServer', x=-170.45, y=76.00, z=450.66], EntityPig['Pig'/587, l='MpServer', x=-191.51, y=72.00, z=479.25], EntityPig['Pig'/588, l='MpServer', x=-188.50, y=78.00, z=465.73], EntityPig['Pig'/589, l='MpServer', x=-180.44, y=74.00, z=471.62], EntityPig['Pig'/590, l='MpServer', x=-182.39, y=74.00, z=472.27], EntityCreeper['Creeper'/337, l='MpServer', x=-157.50, y=19.00, z=349.50], EntityZombie['Zombie'/338, l='MpServer', x=-158.50, y=13.00, z=367.50], EntitySkeleton['Skeleton'/339, l='MpServer', x=-159.50, y=46.00, z=382.50], EntityChicken['Chicken'/598, l='MpServer', x=-174.97, y=76.00, z=443.01], EntityChicken['Chicken'/599, l='MpServer', x=-176.98, y=75.00, z=458.55], EntityItem['item.item.egg'/600, l='MpServer', x=-176.98, y=76.00, z=451.90], EntityPig['Pig'/604, l='MpServer', x=-198.50, y=84.00, z=478.64], EntityPig['Pig'/606, l='MpServer', x=-193.80, y=88.00, z=455.74], EntitySheep['Sheep'/607, l='MpServer', x=-170.75, y=63.00, z=421.81], EntityPig['Pig'/608, l='MpServer', x=-170.55, y=68.00, z=426.39], EntityPig['Pig'/612, l='MpServer', x=-216.72, y=84.00, z=478.42], EntityChicken['Chicken'/613, l='MpServer', x=-212.05, y=88.00, z=465.57], EntityItem['item.item.egg'/614, l='MpServer', x=-212.39, y=88.00, z=465.11], EntityPig['Pig'/620, l='MpServer', x=-211.77, y=91.00, z=455.45], EntityPig['Pig'/621, l='MpServer', x=-219.50, y=92.00, z=455.98], EntitySkeleton['Skeleton'/622, l='MpServer', x=-225.50, y=19.00, z=468.50], EntityPig['Pig'/624, l='MpServer', x=-245.42, y=85.00, z=485.70], EntityPig['Pig'/625, l='MpServer', x=-250.50, y=82.00, z=484.75], EntitySheep['Sheep'/631, l='MpServer', x=-239.74, y=75.00, z=456.55], EntitySheep['Sheep'/632, l='MpServer', x=-236.29, y=75.00, z=457.20], EntityPig['Pig'/633, l='MpServer', x=-224.51, y=75.00, z=448.32], EntityPig['Pig'/634, l='MpServer', x=-251.49, y=73.00, z=477.25], EntitySheep['Sheep'/635, l='MpServer', x=-246.70, y=73.00, z=467.80], EntityCreeper['Creeper'/636, l='MpServer', x=-213.45, y=89.00, z=432.84], EntityCreeper['Creeper'/640, l='MpServer', x=-201.18, y=56.00, z=405.60], EntityCreeper['Creeper'/641, l='MpServer', x=-257.99, y=31.00, z=467.50], EntityBat['Bat'/642, l='MpServer', x=-286.90, y=34.16, z=487.10], EntityPig['Pig'/643, l='MpServer', x=-281.45, y=62.04, z=489.45], EntityBat['Bat'/646, l='MpServer', x=-228.75, y=59.10, z=435.39], EntityZombie['Zombie'/647, l='MpServer', x=-235.75, y=57.00, z=438.18], EntitySkeleton['Skeleton'/648, l='MpServer', x=-233.24, y=74.00, z=432.50], EntityPig['Pig'/649, l='MpServer', x=-251.45, y=73.00, z=460.63], EntityPig['Pig'/650, l='MpServer', x=-243.46, y=74.00, z=457.22], EntityCreeper['Creeper'/661, l='MpServer', x=-227.50, y=53.00, z=419.17], EntitySkeleton['Skeleton'/662, l='MpServer', x=-228.69, y=91.00, z=421.51], EntitySpider['Spider'/663, l='MpServer', x=-230.89, y=81.10, z=428.30], EntityPig['Pig'/664, l='MpServer', x=-280.49, y=72.00, z=464.30], EntitySheep['Sheep'/666, l='MpServer', x=-248.27, y=68.00, z=445.49], EntityPig['Pig'/667, l='MpServer', x=-254.22, y=68.00, z=437.52], EntitySkeleton['Skeleton'/668, l='MpServer', x=-254.50, y=68.00, z=438.50], EntityCreeper['Creeper'/674, l='MpServer', x=-224.78, y=53.00, z=414.58], EntityBat['Bat'/420, l='MpServer', x=-210.25, y=47.10, z=394.25], EntityCreeper['Creeper'/421, l='MpServer', x=-213.84, y=46.00, z=399.61], EntitySkeleton['Skeleton'/422, l='MpServer', x=-169.50, y=32.00, z=391.50], EntityCow['Cow'/423, l='MpServer', x=-175.84, y=63.00, z=392.56], EntityPig['Pig'/424, l='MpServer', x=-171.78, y=64.00, z=387.47], EntityZombie['Zombie'/425, l='MpServer', x=-215.92, y=47.00, z=400.47], EntityBat['Bat'/426, l='MpServer', x=-217.56, y=53.10, z=406.75], EntityBat['Bat'/427, l='MpServer', x=-213.75, y=52.10, z=404.48], EntityPlayerSP['JameMcDougal'/419, l='MpServer', x=-215.36, y=67.00, z=414.66], EntityItem['item.item.darkutils.material.wither'/430, l='MpServer', x=-215.75, y=67.00, z=417.13], EntityItem['item.item.bone'/431, l='MpServer', x=-215.88, y=67.00, z=417.13], EntityItem['item.item.swordStone'/432, l='MpServer', x=-215.16, y=67.00, z=417.13], EntityItem['item.item.coal'/433, l='MpServer', x=-215.88, y=67.00, z=417.13], EntityItem['item.item.swordStone'/434, l='MpServer', x=-215.13, y=67.00, z=417.56], EntityVindicator['Vindicator'/435, l='MpServer', x=-215.37, y=69.00, z=425.62], EntityVindicator['Vindicator'/436, l='MpServer', x=-213.96, y=69.00, z=423.25], EntityVindicator['Vindicator'/437, l='MpServer', x=-218.21, y=69.00, z=420.74], EntityVindicator['Vindicator'/438, l='MpServer', x=-218.42, y=69.00, z=425.44], EntityMinecartHopper['Minecart with Hopper'/195, l='MpServer', x=-217.50, y=68.06, z=348.50], EntityMinecartHopper['Minecart with Hopper'/196, l='MpServer', x=-217.50, y=68.06, z=347.50], EntityMinecartHopper['Minecart with Hopper'/197, l='MpServer', x=-217.50, y=68.06, z=346.50], EntityMinecartHopper['Minecart with Hopper'/198, l='MpServer', x=-217.50, y=68.06, z=345.50], EntityWolf['Wolf'/199, l='MpServer', x=-223.30, y=64.00, z=365.26], EntityItem['item.item.melon'/200, l='MpServer', x=-211.88, y=65.94, z=361.87], EntityItemFrame['entity.ItemFrame.name'/201, l='MpServer', x=-209.50, y=68.50, z=369.03], EntityItemFrame['entity.ItemFrame.name'/202, l='MpServer', x=-209.50, y=67.50, z=369.03], EntityItemFrame['entity.ItemFrame.name'/203, l='MpServer', x=-210.50, y=67.50, z=369.03], EntityItemFrame['entity.ItemFrame.name'/204, l='MpServer', x=-210.50, y=68.50, z=369.03], EntityItemFrame['entity.ItemFrame.name'/205, l='MpServer', x=-208.50, y=68.50, z=369.03], EntityArmorStand['Armor Stand'/206, l='MpServer', x=-211.50, y=74.00, z=371.50], EntityWolf['Wolf'/207, l='MpServer', x=-223.30, y=64.00, z=369.70], EntityItemFrame['entity.ItemFrame.name'/208, l='MpServer', x=-210.50, y=66.50, z=369.03], EntityItemFrame['entity.ItemFrame.name'/209, l='MpServer', x=-209.50, y=66.50, z=369.03], EntityChunkData['entity.chunkdata.name'/210, l='MpServer', x=-216.00, y=512.00, z=376.00], EntityZombie['Zombie'/470, l='MpServer', x=-271.50, y=67.00, z=416.50], EntityPig['Pig'/475, l='MpServer', x=-294.70, y=70.00, z=445.49], EntityWolf['Wolf'/489, l='MpServer', x=-224.45, y=64.00, z=366.24], EntityWolf['Wolf'/490, l='MpServer', x=-224.44, y=64.00, z=367.28], EntityArmorStand['Armor Stand'/235, l='MpServer', x=-204.50, y=62.00, z=367.50], EntityVillager['Villager'/236, l='MpServer', x=-193.65, y=65.00, z=360.35], EntityItemFrame['entity.ItemFrame.name'/237, l='MpServer', x=-207.50, y=68.50, z=369.03], EntityItemFrame['entity.ItemFrame.name'/238, l='MpServer', x=-207.50, y=67.50, z=369.03], EntityEnderman['Enderman'/500, l='MpServer', x=-230.52, y=17.00, z=347.81], EntityEnderman['Enderman'/501, l='MpServer', x=-226.50, y=17.00, z=345.50], EntityCreeper['Creeper'/503, l='MpServer', x=-246.50, y=16.00, z=354.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2655)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:393)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Linux (amd64) version 4.10.13-1-ARCH
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1193312624 bytes (1138 MB) / 2650181632 bytes (2527 MB) up to 4241293312 bytes (4044 MB)
	JVM Flags: 5 total; -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn512M
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
	FML: MCP 9.38 Powered by Forge 13.20.0.2285 Optifine OptiFine_1.11.2_HD_U_C1 48 mods loaded, 48 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2285.jar) 
	UCHIJAAAA	forge{13.20.0.2285} [Minecraft Forge] (forge-1.11.2-13.20.0.2285.jar) 
	UCHIJAAAA	ivtoolkit{1.3.3} [IvToolkit] (minecraft.jar) 
	UCHIJAAAA	potioncore_coremod{1.5.2_for_1.11.2} [Potion Core Coremod] (minecraft.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar) 
	UCHIJAAAA	achunkloader{1.11-1.2.0} [A Chunk Loader] (achunkloader-1.11.2-1.2.0.jar) 
	UCHIJAAAA	biomesoplenty{6.1.0.2205} [Biomes O' Plenty] (BiomesOPlenty-1.11.2-6.1.0.2205-universal.jar) 
	UCHIJAAAA	bookshelf{1.5.0.371} [Bookshelf] (Bookshelf-1.11.2-1.5.0.371.jar) 
	UCHIJAAAA	ceramics{1.11.2-1.2.0} [Ceramics] (Ceramics-1.11.2-1.2.0.jar) 
	UCHIJAAAA	chameleon{1.11.2-3.1.0} [Chameleon] (Chameleon-1.11.2-3.1.0.jar) 
	UCHIJAAAA	d3core{1.3.0.66} [D??Core] (D3Core-1.11.2-1.3.0.66.jar) 
	UCHIJAAAA	darkutils{1.2.0.126} [Dark Utilities] (DarkUtilities-1.11.2-1.2.0.126.jar) 
	UCHIJAAAA	extrautils2{1.0} [extrautils2] (extrautils2-1.11.2-1.4.1.jar) 
	UCHIJAAAA	ezstorage{2.4.1} [EZStorage 2] (ezstorage-2.4.1-[1.11.2].jar) 
	UCHIJAAAA	fastleafdecay{v12} [Fast Leaf Decay] (FastLeafDecay-v12.jar) 
	UCHIJAAAA	findercompass{1.11.2} [Finder Compass] (FinderCompass-1.11.2.jar) 
	UCHIJAAAA	ftbl{0.0.0} [FTBLib] (FTBLib-1.1x-3.6.5.jar) 
	UCHIJAAAA	gravestone{1.7.2} [Gravestone] (GraveStone Mod 1.7.2.jar) 
	UCHIJAAAA	inventorytweaks{1.62+beta.86.e69c6bf} [Inventory Tweaks] (InventoryTweaks-1.62+beta.86.jar) 
	UCHIJAAAA	ironchest{1.11.2-7.0.18.800} [Iron Chest] (ironchest-1.11.2-7.0.18.800.jar) 
	UCHIJAAAA	jei{4.3.3.270} [Just Enough Items] (jei_1.11.2-4.3.3.270.jar) 
	UCHIJAAAA	journeymap{1.11.2-5.4.6} [JourneyMap] (journeymap-1.11.2-5.4.6.jar) 
	UCHIJAAAA	lumberjack{1.0} [lumberjack] (Lumberjack-1.11.2-1.3.1.48.jar) 
	UCHIJAAAA	mantle{1.11.2-1.2.0.26} [Mantle] (Mantle-1.11.2-1.2.0.26.jar) 
	UCHIJAAAA	metamorph{1.1.3} [Metamorph] (metamorph-1.1.3-1.11.2.jar) 
	UCHIJAAAA	shetiphiancore{3.4.4} [ShetiPhian-Core] (shetiphiancore-1.11.0-3.4.4.jar) 
	UCHIJAAAA	multistorage{1.3.6} [Multi-Storage] (multistorage-1.11.0-1.3.6.jar) 
	UCHIJAAAA	packingtape{1.11.0-0.6.1} [Packing Tape] (PackingTape-1.11.0-0.6.1.jar) 
	UCHIJAAAA	potioncore{1.5.2_for_1.11.2} [Potion Core] (PotionCore-1.5.2_for_1.11.2.jar) 
	UCHIJAAAA	reccomplex{1.3.2} [Recurrent Complex] (RecurrentComplex-1.3.2.jar) 
	UCHIJAAAA	rftools{6.01} [RFTools] (rftools-1.1x-6.01.jar) 
	UCHIJAAAA	rftoolsdim{5.02} [RFTools Dimensions] (rftoolsdim-1.1x-5.02.jar) 
	UCHIJAAAA	roguelike{1.6.6} [Roguelike Dungeons] (RoguelikeDungeons-1.11.2-1.6.6.jar) 
	UCHIJAAAA	examplemod{1.0} [examplemod] (SimpleGrinder-3.132.R11112.jar) 
	UCHIJAAAA	simplegrinder{3.122.R1112} [Simple Grinder] (SimpleGrinder-3.132.R11112.jar) 
	UCHIJAAAA	simplyconveyors{3.0.6} [Simply Conveyors & More] (SimplyConveyors-3.0.6.jar) 
	UCHIJAAAA	slimer{1.0} [Slime Chunker] (slimer-1.2.jar) 
	UCHIJAAAA	spawnercraft{4.0} [SpawnerCraft] (SpawnerCraft 1.11.2-4.0.0.jar) 
	UCHIJAAAA	storagedrawers{1.11.2-4.2.8} [Storage Drawers] (StorageDrawers-1.11.2-4.2.8.jar) 
	UCHIJAAAA	subcommonlib{1.1.3.0} [Subaraki's Common Library] (sublib-1.11-1.1.3.0.jar) 
	UCHIJAAAA	tconstruct{1.11.2-2.7.0.26} [Tinkers' Construct] (TConstruct-1.11.2-2.7.0.26.jar) 
	UCHIJAAAA	telepads{1.11 v1.0.1.1} [Telepads] (telepads-1.11-1.0.1.1.jar) 
	UCHIJAAAA	waila{1.7.1} [waila] (Waila-1.7.1_1.11.2.jar) 
	UCHIJAAAA	wailaharvestability{1.1.9} [Waila Harvestability] (WailaHarvestability-mc1.11-1.1.9.jar) 
	UCHIJAAAA	xpbook{0.0.2-beta} [XPBook] (xpbook-1.11.2-0.0.2-beta.jar) 
	UCHIJAAAA	yabba{1.11.2-0.5.1} [YABBA] (YABBA-1.11.2-0.5.1.jar) 
	Loaded coremods (and transformers): 
FCFMLCorePlugin (FinderCompass-1.11.2.jar)
  atomicstryker.findercompass.client.coremod.FCTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.62+beta.86.jar)
  invtweaks.forge.asm.ContainerTransformer
IvToolkit (IvToolkit-1.3.3.jar)
  
BookshelfLoadingPlugin (Bookshelf-1.11.2-1.5.0.371.jar)
  net.darkhax.bookshelf.asm.BookshelfTransformerManager
PotionCoreFMLLoadingPlugin (PotionCore-1.5.2_for_1.11.2.jar)
  com.tmtravlr.potioncore.asm.ArmorHandlerTransformer
ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.4.jar)
  shetiphian.core.asm.ClassTransformer
	GL info: ' Vendor: 'X.Org' Version: '3.0 Mesa 17.0.5' Renderer: 'Gallium 0.4 on AMD ARUBA (DRM 2.49.0 / 4.10.13-1-ARCH, LLVM 4.0.0)'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	d3core: Debug: false Silliness: true AprilFools: true PastPost:true
	Launched Version: 1.11.2-forge1.11.2-13.20.0.2285
	LWJGL: 2.9.4
	OpenGL: Gallium 0.4 on AMD ARUBA (DRM 2.49.0 / 4.10.13-1-ARCH, LLVM 4.0.0) GL version 3.0 Mesa 17.0.5, X.Org
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Faithful Mods 1.11.2-rv4.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD A10-5800K APU with Radeon(tm) HD Graphics
	OptiFine Version: OptiFine_1.11.2_HD_U_C1
	Render Distance Chunks: 9
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.0 Mesa 17.0.5
	OpenGlRenderer: Gallium 0.4 on AMD ARUBA (DRM 2.49.0 / 4.10.13-1-ARCH, LLVM 4.0.0)
	OpenGlVendor: X.Org
	CpuCount: 4

**Comment by siskulous** [comment]
Ok, I should really check versions before reporting bugs. Seems I duplicated a bug that's already been reported and fixed in the latest release. Sorry, I'll close this one.
